# Generated by Django 2.2.4 on 2020-05-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('data_expiracao', models.DateTimeField()),
                ('prioridade', models.CharField(choices=[('a', 'Alta'), ('b', 'Baixa'), ('n', 'Normal')], max_length=1)),
            ],
        ),
    ]
